### ISSUE TITLE
Angular 6 integration

### ISSUE THREAD

**Issue by DejanNemet** [MurhafSousli/ngx-teximate#17]
Hello,

Is anyone else having problems integrating "teximate" into their angular 6 project?

I've impotred it into my root module (app.module.ts), imported the animate.css into my styles.scss.
I had to import "TeximateOptions" and "TeximateOrder" from "ng-teximate/helper/teximate.class" in my controller to remove "Can't find name" error. And I still cant make angular recognize <teximate> as a known element ( 'teximate' is not a known element  -  error).

I bet I overlooked something small, but cant find it for the life of me...
Any help would be appreciated.

**Comment by DejanNemet** [comment]
Thank you for the quick response and thank you for considering to optimize it for Angular 6.

**Comment by danieldanielecki** [comment]
@DejanNemet not sure how with Angular 6, but on Angular 8 I got it working without any extra effort, but dependencies in `package.json` could've been updated, because as of now these link to Angular 7's dependencies (cc: @MurhafSousli).
